server.port=8080

# 数据库连接配置
spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.url=jdbc:h2:file:${user.home}/.lms/h2/lms;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.username=root
spring.datasource.password=test

# sql初始化配置
# mode=embedded时，配置file模式，不会执行sql初始化脚本；file模式如果要支持初始化脚本，需要配置mode=always
spring.sql.init.mode=always
#spring.sql.init.mode=embedded
spring.sql.init.schema-locations=classpath:db/schema-h2.sql
spring.sql.init.data-locations=classpath:db/data-h2.sql

# 打开 H2 数据库控制台
spring.h2.console.enabled=true

# 调试的时候可以打开，可以看到初始化脚本是否执行
logging.level.org.springframework.jdbc.datasource.init=DEBUG

mybatis-plus.mapper-locations=classpath:mapper/*.xml

# 配置编码格式，避免在 H2 控制台查看数据时，看到中文乱码
spring.servlet.encoding.charset=UTF-8